name: which
version: 0.1.3
author: Sean Eagan <seaneagan1@gmail.com>
description: Like unix which(1).  Check for and locate installed executables.
homepage: https://github.com/seaneagan/which.dart
dependencies:
  path: '>=1.3.1 <2.0.0'
  when: '>=0.2.0 <0.3.0'
dev_dependencies:
  mockito: '>=0.8.1 <0.9.0'
  unittest: '>=0.11.4 <0.12.0'
